import { useState, useEffect } from "react";
import { Award, Download, Calendar } from "lucide-react";
import toast from "react-hot-toast";
import API from "../../services/api";
import LoadingSpinner from "../../components/LoadingSpinner";
import EmptyState from "../../components/EmptyState";

export default function MyCertificatesPage() {
  const [certificates, setCertificates] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    API.get("/certificates/me")
      .then((res) => setCertificates(res.data))
      .catch(() => setCertificates([]))
      .finally(() => setLoading(false));
  }, []);

  const handleDownload = async (certNumber) => {
    try {
      const res = await API.get(`/certificates/download/${certNumber}`, {
        responseType: "blob",
      });
      const url = window.URL.createObjectURL(new Blob([res.data]));
      const link = document.createElement("a");
      link.href = url;
      link.setAttribute("download", `Certificate_${certNumber}.pdf`);
      document.body.appendChild(link);
      link.click();
      link.remove();
      toast.success("Certificate downloaded!");
    } catch {
      toast.error("Download failed. Try again.");
    }
  };

  if (loading) return <LoadingSpinner />;

  return (
    <div>
      <div className="mb-6">
        <h2 className="text-xl font-semibold text-gray-900 font-[Poppins]">
          My Certificates
        </h2>
        <p className="text-sm text-gray-500 mt-1">
          Download your participation certificates
        </p>
      </div>

      {certificates.length === 0 ? (
        <EmptyState
          icon={<Award size={28} />}
          title="No certificates yet"
          subtitle="Attend events and your certificates will appear here once generated by the organizer."
        />
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {certificates.map((cert) => (
            <div
              key={cert.certificate_id}
              className="bg-white border border-gray-100 rounded-2xl p-5
                hover:shadow-sm transition-shadow"
            >
              {/* Icon */}
              <div className="w-12 h-12 bg-indigo-50 rounded-xl flex items-center
                justify-center mb-4">
                <Award size={24} className="text-indigo-600" />
              </div>

              <h3 className="font-semibold text-gray-900 text-sm font-[Poppins] mb-1
                line-clamp-2">
                {cert.event_title}
              </h3>

              <div className="flex items-center gap-1.5 text-xs text-gray-500 mb-1">
                <Calendar size={12} />
                {cert.event_date}
              </div>

              <p className="text-xs text-gray-400 mb-4">
                Certificate No: {cert.certificate_number}
              </p>

              <button
                onClick={() => handleDownload(cert.certificate_number)}
                className="w-full flex items-center justify-center gap-2 py-2.5
                  rounded-xl bg-indigo-600 text-white text-xs font-medium
                  hover:bg-indigo-700 transition-colors"
              >
                <Download size={14} /> Download PDF
              </button>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}